[package]
name = "du-gui-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio"] }
iced_table = "0.12.0"
dirs = "5.0"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
