#!/bin/bash

cargo build --release --target x86_64-pc-windows-gnu
cd target/x86_64-pc-windows-gnu/release/
zip -r ../../../findbigfolders_0.2_beta-x86_64-windows.zip du-gui-rs.exe
cd ../../../

exit 0